{% set name = "sniffio" %}
{% set version = "1.2.0" %}
{% set sha256 = "c4666eecec1d3f50960c6bdf61ab7bc350648da6c126e3cf6898d8cd4ddcd3de" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - contextvars >=2.1  # [py<37]

test:
  imports:
    - {{ name }}
    - {{ name }}._tests

about:
  home: https://github.com/python-trio/sniffio
  license: APACHE
  license_family: APACHE
  license_file: LICENSE.APACHE2
  summary: Sniff out which async library your code is running under
  doc_url: https://sniffio.readthedocs.io
